"""Initial migration

Revision ID: 53a11a2307f6
Revises: ac041e6cb502
Create Date: 2025-05-20 03:16:56.056013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53a11a2307f6'
down_revision = 'ac041e6cb502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('reserved_stock_xl')
        batch_op.drop_column('reserved_stock_m')
        batch_op.drop_column('reserved_stock_l')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reserved_stock_s')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_stock_s', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reserved_stock_l', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reserved_stock_m', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reserved_stock_xl', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
