"""Add delivery address fields to Order model

Revision ID: b2c90c409486
Revises: 7f039db6ebef
Create Date: 2025-05-11 15:03:31.416530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c90c409486'
down_revision = '7f039db6ebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('delivery_city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('delivery_state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('delivery_pincode', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('delivery_phone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_phone')
        batch_op.drop_column('delivery_pincode')
        batch_op.drop_column('delivery_state')
        batch_op.drop_column('delivery_city')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
